---
author: "Xudong Sun"
title: "Deep reinforcement learning in R"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
#output:
#  html_document:
#    toc: true
#    toc_float:
#      collapsed: true
#      smooth_scroll: false
#    dev: svg
vignette: >
  %\VignetteIndexEntry{Deep reinforcement learning in R}
  %\VignetteEngine{knitr::knitr}
  %\usepackage[UTF-8]{inputenc}
---

```{r setup, include = FALSE, cache = FALSE}
library(rlR)
set.seed(123)
knitr::opts_chunk$set(cache = TRUE, collapse = FALSE, dev = "svg", fig.height = 3.5)
knitr::knit_hooks$set(document = function(x){
  gsub("```\n*```r*\n*", "", x)
})
library(reticulate)
os = import("os")
os$environ[["TF_CPP_MIN_LOG_LEVEL"]]="3"
```

# rlR: Deep Reinforcement learning in R

## Installation
```{r}
library(devtools)
devtools::install_github("compstat-lmu/rlR", dependencies = TRUE)
```

## Usage
```{r}
library(rlR)
env = makeGymEnv("CartPole-v0")
listAvailAgent()
```


```{r}
agent = makeAgent("AgentDQN", env)
agent$updatePara("console", FALSE)
system.time({
#perf = agent$learn(1000)  # umcomment this line to run yourself which might take a while
})
#perf$plot()
```
