---
title: "Custom Configuration"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
    dev: svg
vignette: >
  %\VignetteIndexEntry{Custom Configuration}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE, cache = FALSE}
library(rlR)
set.seed(123)
knitr::opts_chunk$set(cache = TRUE, collapse = FALSE, dev = "svg", fig.height = 3.5)
knitr::knit_hooks$set(document = function(x){
  gsub("```\n*```r*\n*", "", x)
})
library(reticulate)
#os = import("os")
#os$environ[["TF_CPP_MIN_LOG_LEVEL"]]="3"
```


# Configure

```{r eval=TRUE}
librar(rlR)
options(width=1000)
listAvailConf()[, .(name, note)]
```

```{r}
listAvailAgent()
```

```{r eval=TRUE}
conf = getDefaultConf("AgentDQN")
conf$show()
conf$set(render = FALSE, console = FALSE)
```

```{r learn, eval=FALSE} 
agent = initAgent("AgentDQN", env, conf)
agent$customizeBrain(makeValueNet, "value_fun")
ptmi = proc.time()
agent$learn(200L)  
proc.time() - ptmi
```

```{r mplot, eval=FALSE,fig.path="inst/figures/", warning=FALSE, message=FALSE, eval=FALSE}
agent$plotPerf(F)
```
