context("gym_continuous")
test_that("test ddpg works", {
  skip_on_cran()
  env = makeGymEnv("Pendulum-v0")
  conf = getDefaultConf("AgentDQN")
  conf$set(replay.memname = "Online")
  agent = makeAgent("AgentDDPG", env, conf)
  agent$learn(1)
  expect_true(TRUE)
})
