context("zzz")
test_that("zzz", {
  rlr_test_if_tensorflow_works()
  checkPyDep()
  listGymEnvs()
  env = makeGymEnv("CartPole-v0")
  listAvailAgent(env)
  rlr_test_if_tensorflow_works()
  rlr_test_if_gym_works()
  rlr_test_if_keras_works()
  expect_true(TRUE)
})
