context("custom_environment")
test_that("basic environment works", {
  env = rlR::Environment$new()
  env$overview()
  conf = getDefaultConf("AgentDQN")
  agent = initAgent("AgentDQN", env, conf)
  perf = agent$learn(12)
  expect_class(perf, "Performance")
})
test_that("Gym constructor Works", {
  env = Environment$new("Pong-v0")
  env$reset()
  env$step(1)
  env$afterAll()
  env = makeGymEnv(name = "CartPole-v0")
  #env$reset()
  #env$step(1)
  #env$afterAll()
  sr = Surrogate$new(3, c(2, 5, 7), createModel.fun = NULL)
  expect_error(sr$train())
  expect_error(sr$pred())
})
