context("custom_environment")
test_that("Gym constructor Works", {
  env = Environment$new("Pong-v0")
  env$reset()
  env$step(1)
  env$afterAll()
  rlr_test_if_tensorflow_works()
  rlr_test_if_gym_works()
  rlr_test_if_keras_works()
  listAvailEnvs()
  #snapshot("pong-v0")
  env = makeGymEnv(name ="CartPole-v0")
  env$reset()
  env$step(1)
  env$afterAll()
  AgentDDPG$new(env, getDefaultConf("AgentDQN"))
  sr = Surrogate$new(3, c(2,5,7), createModel.fun = NULL)
  expect_error(sr$train())
  expect_error(sr$pred())
  snapshot(sname = "Pong-v0")
})
