context("custom_environment")
test_that("Gym constructor Works", {
  env = Environment$new("Pong-v0")
  env$reset()
  env$step(1)
  env$afterAll()
  env = makeGymEnv(name = "CartPole-v0")
  #env$reset()
  #env$step(1)
  #env$afterAll()
  sr = Surrogate$new(3, c(2, 5, 7), createModel.fun = NULL)
  expect_error(sr$train())
  expect_error(sr$pred())
})
